### ISSUE TITLE
1.8.1 is not support in react-native 0.41.2

### ISSUE THREAD

**Issue by qiangspecial** [react-native-community/react-native-navbar#233]
My project is depend some npm package, and the package depend `react-native-navbar^1.7.1`, so when I build my project, it will use `react-native-navbar@1.8.1`, so can you release new version 1.8.2 fix this bug?

Forgive me so bad English!

**Comment by Kureev** [comment]
Hey @qiangspecial,

You don't have to be be shy because of your English, it isn't my native language either! 😉 
I have a couple of questions for you:

1. Can you provide us a stack trace of the issue you experience? It is hard to fix an issue you don't know much about
2. For now (till the issue is fixed), can you try to freeze dependency version by removing `^` in the beginning of the dependency version. It'll make sure you have a `1.8.1` instead of `1.8.x` 😉

**Comment by qiangspecial** [comment]
hi @Kureev , Thank you for answering me！
I think I found the reason for the problem，there is npm cache in my company's LAN，so when I run `npm i` and the `dependencies` is like this `{"react-native-navbar": "^1.7.1"}`, I will installed `react-native-navbar@1.8.1` from LAN npm cache。

you can close this issue
